name = "AbstractAnalysis"
uuid = "86512db7-604a-4b90-aeec-df6b673a43d4"
version = "0.2.0"
authors = ["Michael Reed"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
StaticVectors = "20fadf95-9e3d-483c-97cd-cab2760e7998"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[weakdeps]
Mods = "7475f97c-0381-53b1-977b-4c60186c8d62"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[extensions]
ModsExt = "Mods"
PrimesExt = "Primes"

[compat]
julia = "1"
ElasticArrays = "1"
StaticVectors = "1"
Combinatorics = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
